---
- name: Build and Deploy todolist-fe 
  hosts: app
  vars:
    ci_cd_namespace: ravi-ci-cd
    dev_namespace: ravi-dev
    test_namespace: ravi-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
